### ISSUE TITLE
Wrong DMR identity for DMR-ID 2314046 

### ISSUE THREAD

**Issue by palkoc** [PD1LOI/MD380tools#3]
Hi Loui,
it seems there is a wrong name/callsign assigned to DMR ID: 2314046. It should be OM0WT, not OM3KLL.  You can check it on https://radioid.net/database/search#! or http://ham-digital.org/dmr-userreg.php?callsign=OM0WT
Please can you check it? 
Thanks.
73, Pavol OM0WT

**Comment by PD1LOI** [comment]
We Fix it next update.

Op wo 29 mei 2019 22:39 schreef palkoc <notifications@github.com>:

**Comment by javastraat** [comment]
done closed

**Comment by palkoc** [comment]
Guys, it's still wrong.

WRONG: 2314046,OM0WT,EMCOMM Slovakia,Kosice,Kosicky,,SK 

CORRECT: 2314046,OM0WT, Pavol Calfa, Kosice,Kosicky,,SK

Thanks,

73, Pavol
